services:
  mysql-desafio-itau:
    image: mysql:8.0.36
    container_name: mysql-desafio-itau
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: desafio_itau_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
